### ISSUE TITLE
Trouble making domain settings apply to links in course

### ISSUE THREAD

**Issue by jstanley14** [OSCELOT/bb-basiclti#1]
I need to set up the LTI configuration on the domain level, so that it would apply to all LTI links matching that domain; I would need to enable outcomes support for all of those links as well.

When I configure the domain, key, secret, and options in the Basic LTI Tool Domains page, everything appears fine, with the green check under Status. However, I’m not able to make Blackboard actually apply those settings to the links in my courses (created through importing a CC1.2 course export package). It simply says ‘Launch Error, Could not launch link, the Tool Provider has not been configured yet’. The domain it is using for the link does match the domain I set up in the LTI tool configuration.

Am I missing some step to make Blackboard actually apply those domain settings to my course? I can make the links work by going to Packages and Utilities -> Manage LTI Links and configuring the key and secret there, but then I’m not able to enable outcomes on those links, which is necessary.

**Comment by spvickers** [comment]
I suspect that your LTI links are using the native LTI support in Blackboard Learn and are not using this building block.  You either need to configure the domain settings using the Learn LTI interface, or replace the links to ones created via this building block.

**Comment by jstanley14** [comment]
Is it possible to create the links to use this building block through a CC1.2 course package import?

**Comment by spvickers** [comment]
No, sorry, the building block does not support importing common cartridges and the Blackboard Learn process for importing them only uses its own functionality for creating LTI links.

**Comment by jstanley14** [comment]
Sorry to hear that, but thanks for your help and responsiveness.
